config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :sessions, only: [:create, :new]
  delete "sign_out", to: "sessions#destroy", as: :destroy_session
  resources :registrations, only: [:create, :new] do
    collection do
      get "verification"
      get "verify"
    end
  end
  resources :landing, only: [:index]
  root "landing#index"
  resources :sites do
    resources :location_urls, only: [:index]
    resources :countries, only: [:index]
    resources :referrer_sources, only: [:index]
    resources :traffic_mediums, only: [:index]
    resources :traffic_sources, only: [:index]
    resources :traffic_campaigns, only: [:index]
    resources :browsers, only: [:index]
    resources :device_types, only: [:index]
    resources :oses, only: [:index]

    resources :site_connections, only: [:index, :new, :show, :destroy, :create]
    resources :measurement_protocols, only: [:index, :new, :show, :destroy, :create]
    member do
      get "snippet"
      get "debug"
    end
    resources :settings, only: %i[index] do
      collection do
        get "general"
        patch "update_general"
      end

      collection do
        get "visibility"
        patch "update_visibility"
      end
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/sources/_nav.html.erb
<div class="w-full flex justify-between">
  <h3 class="font-bold dark:text-gray-100">Top Traffics</h3>
  <ul class="flex font-medium text-xs text-gray-500 dark:text-gray-400 space-x-2">
    <li class="<%= source_tab_class(:referrer_source) %>"><%= link_to "Referral", site_path(@site, **params.permit.merge(source_meniu: :referrer_source), anchor: 'top_traffics') %></li>
    <li class="<%= source_tab_class(:traffic_medium) %>"><%= link_to "Medium", site_path(@site, **params.permit.merge(source_meniu: :traffic_medium), anchor: 'top_traffics') %></li>
    <li class="<%= source_tab_class(:traffic_source) %>"><%= link_to "Source", site_path(@site, **params.permit.merge(source_meniu: :traffic_source), anchor: 'top_traffics') %></li>
    <li class="<%= source_tab_class(:traffic_campaign) %>"><%= link_to "Campaign", site_path(@site,  **params.permit.merge(source_meniu: :traffic_campaign), anchor: 'top_traffics') %></li>
  </ul>
</div>

app/views/shared/sources/_referrer_source.html.erb
<div class="stats-item relative bg-white dark:bg-gray-825 shadow-xl rounded p-4" style="height: 436px;">
  <div class="fade-enter-active">
    <%= render partial: 'shared/sources/nav' %>
    <div class="flex items-center mt-3 mb-2 justify-between text-gray-500 text-xs font-bold tracking-wide"><span>Referral</span><span>Visitors</span>
    </div>
    <div style="position: relative;">
      <% @top_referrer_sources.each do |source| %>
        <% @max_source ||= source.count %>
        <div class="flex items-center justify-between my-1 text-sm">
          <div class="w-full h-8" style="max-width: calc(100% - 4rem);">
            <div class="bg-blue-50 dark:bg-gray-500 dark:bg-opacity-15" style="width:  <%= number_to_percentage(100 * source.count / @max_source.to_f, precision: 2) %>; height: 30px;">

            </div>
            <span class="flex px-2 dark:text-gray-300" style="margin-top: -26px;">
              <%= link_to site_path(@site, request.query_parameters.merge(referrer_source: source.referrer_source)), class: 'block truncate hover:underline' do %>
                <img src="<%= domain_icon_url(source.referrer_source) %>" referrerpolicy="no-referrer" class="inline h-4 w-4 mr-2 align-middle -mt-px"><%= source.referrer_source %>
              <% end%>
            </span>
          </div><span class="font-medium dark:text-gray-200"><%= pretty_num(source.count) %></span>
        </div>
      <% end %>

    </div>

    <div class="text-center w-full absolute bottom-0 left-0 pb-3">
      <a class="leading-snug font-bold text-sm text-gray-500 dark:text-gray-400 hover:text-red-500 dark:hover:text-red-400 transition tracking-wide" href="<%= site_referrer_sources_path(@site, request.query_parameters) %>"><svg class="feather mr-1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="margin-top: -2px;"><path d="M8 3H5a2 2 0 0 0-2 2v3m18 0V5a2 2 0 0 0-2-2h-3m0 18h3a2 2 0 0 0 2-2v-3M3 16v3a2 2 0 0 0 2 2h3"></path></svg>MORE
      </a>
    </div>
  </div>
</div>

app/views/shared/sources/_traffic_campaign.html.erb
<div class="stats-item relative bg-white dark:bg-gray-825 shadow-xl rounded p-4" style="height: 436px;">
  <div class="fade-enter-active">
    <%= render partial: 'shared/sources/nav' %>
    <div class="flex items-center mt-3 mb-2 justify-between text-gray-500 text-xs font-bold tracking-wide"><span>Traffic Campaign</span><span>Visitors</span>
    </div>
    <div style="position: relative;">
      <% @top_traffic_campaigns.each do |source| %>
        <% @max_campaign ||= source.count %>
        <div class="flex items-center justify-between my-1 text-sm">
          <div class="w-full h-8" style="max-width: calc(100% - 4rem);">
            <div class="bg-blue-50 dark:bg-gray-500 dark:bg-opacity-15" style="width:  <%= number_to_percentage(100 * source.count / @max_campaign.to_f, precision: 2) %>; height: 30px;">

            </div>
            <span class="flex px-2 dark:text-gray-300" style="margin-top: -26px;">
              <%= link_to site_path(@site, request.query_parameters.merge(traffic_campaign: source.traffic_campaign)), class: 'block truncate hover:underline' do %>
               <%= source.traffic_campaign %>
              <% end%>
            </span>
          </div><span class="font-medium dark:text-gray-200"><%= pretty_num(source.count) %></span>
        </div>
      <% end %>

    </div>

    <div class="text-center w-full absolute bottom-0 left-0 pb-3">
      <a class="leading-snug font-bold text-sm text-gray-500 dark:text-gray-400 hover:text-red-500 dark:hover:text-red-400 transition tracking-wide" href="<%= site_traffic_campaigns_path(@site, request.query_parameters) %>"><svg class="feather mr-1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="margin-top: -2px;"><path d="M8 3H5a2 2 0 0 0-2 2v3m18 0V5a2 2 0 0 0-2-2h-3m0 18h3a2 2 0 0 0 2-2v-3M3 16v3a2 2 0 0 0 2 2h3"></path></svg>MORE
      </a>
    </div>
  </div>
</div>

app/views/shared/sources/_traffic_medium.html.erb
<div class="stats-item relative bg-white dark:bg-gray-825 shadow-xl rounded p-4" style="height: 436px;">
  <div class="fade-enter-active">
    <%= render partial: 'shared/sources/nav' %>
    <div class="flex items-center mt-3 mb-2 justify-between text-gray-500 text-xs font-bold tracking-wide"><span>Traffic Medium</span><span>Visitors</span>
    </div>
    <div style="position: relative;">
      <% @top_traffic_mediums.each do |source| %>
        <% @max_medium ||= source.count %>
        <div class="flex items-center justify-between my-1 text-sm">
          <div class="w-full h-8" style="max-width: calc(100% - 4rem);">
            <div class="bg-blue-50 dark:bg-gray-500 dark:bg-opacity-15" style="width:  <%= number_to_percentage(100 * source.count / @max_medium.to_f, precision: 2) %>; height: 30px;">

            </div>
            <span class="flex px-2 dark:text-gray-300" style="margin-top: -26px;">
              <%= link_to site_path(@site, request.query_parameters.merge(traffic_medium: source.traffic_medium)), class: 'block truncate hover:underline' do %>
               <%= source.traffic_medium %>
              <% end%>
            </span>
          </div><span class="font-medium dark:text-gray-200"><%= pretty_num(source.count) %></span>
        </div>
      <% end %>

    </div>

    <div class="text-center w-full absolute bottom-0 left-0 pb-3">
      <a class="leading-snug font-bold text-sm text-gray-500 dark:text-gray-400 hover:text-red-500 dark:hover:text-red-400 transition tracking-wide" href="<%=site_traffic_mediums_path(@site, request.query_parameters)%>"><svg class="feather mr-1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="margin-top: -2px;"><path d="M8 3H5a2 2 0 0 0-2 2v3m18 0V5a2 2 0 0 0-2-2h-3m0 18h3a2 2 0 0 0 2-2v-3M3 16v3a2 2 0 0 0 2 2h3"></path></svg>MORE
      </a>
    </div>
  </div>
</div>

app/views/shared/sources/_traffic_source.html.erb
<div class="stats-item relative bg-white dark:bg-gray-825 shadow-xl rounded p-4" style="height: 436px;">
  <div class="fade-enter-active">
    <%= render partial: 'shared/sources/nav' %>
    <div class="flex items-center mt-3 mb-2 justify-between text-gray-500 text-xs font-bold tracking-wide"><span>Traffic Source</span><span>Visitors</span>
    </div>
    <div style="position: relative;">
      <% @top_traffic_sources.each do |source| %>
        <% @max_source ||= source.count %>
        <div class="flex items-center justify-between my-1 text-sm">
          <div class="w-full h-8" style="max-width: calc(100% - 4rem);">
            <div class="bg-blue-50 dark:bg-gray-500 dark:bg-opacity-15" style="width:  <%= number_to_percentage(100 * source.count / @max_source.to_f, precision: 2) %>; height: 30px;">

            </div>
            <span class="flex px-2 dark:text-gray-300" style="margin-top: -26px;">
              <%= link_to site_path(@site, request.query_parameters.merge(traffic_source: source.traffic_source)), class: 'block truncate hover:underline' do %>
               <%= source.traffic_source %>
              <% end%>
            </span>
          </div><span class="font-medium dark:text-gray-200"><%= pretty_num(source.count) %></span>
        </div>
      <% end %>

    </div>

    <div class="text-center w-full absolute bottom-0 left-0 pb-3">
      <a class="leading-snug font-bold text-sm text-gray-500 dark:text-gray-400 hover:text-red-500 dark:hover:text-red-400 transition tracking-wide" href="<%= site_traffic_sources_path(@site, request.query_parameters) %>"><svg class="feather mr-1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="margin-top: -2px;"><path d="M8 3H5a2 2 0 0 0-2 2v3m18 0V5a2 2 0 0 0-2-2h-3m0 18h3a2 2 0 0 0 2-2v-3M3 16v3a2 2 0 0 0 2 2h3"></path></svg>MORE
      </a>
    </div>
  </div>
</div>

app/views/shared/sources/_utm_campaign.html.erb
<div class="stats-item relative bg-white dark:bg-gray-825 shadow-xl rounded p-4" style="height: 436px;">
  <div class="fade-enter-active">
    <%= render partial: 'shared/sources/nav' %>
    <div class="flex items-center mt-3 mb-2 justify-between text-gray-500 text-xs font-bold tracking-wide"><span>UTM Campaign</span><span>Visitors</span>
    </div>
    <div style="position: relative;">
      <% @top_utm_campaigns.each do |source| %>
        <% @max_campaign ||= source.count %>
        <div class="flex items-center justify-between my-1 text-sm">
          <div class="w-full h-8" style="max-width: calc(100% - 4rem);">
            <div class="bg-blue-50 dark:bg-gray-500 dark:bg-opacity-15" style="width:  <%= number_to_percentage(100 * source.count / @max_campaign.to_f, precision: 2) %>; height: 30px;">

            </div>
            <span class="flex px-2 dark:text-gray-300" style="margin-top: -26px;">
              <%= link_to site_path(@site, request.query_parameters.merge(utm_campaign: source.utm_campaign)), class: 'block truncate hover:underline' do %>
               <%= source.utm_campaign %>
              <% end%>
            </span>
          </div><span class="font-medium dark:text-gray-200"><%= pretty_num(source.count) %></span>
        </div>
      <% end %>

    </div>

    <div class="text-center w-full absolute bottom-0 left-0 pb-3">
      <a class="leading-snug font-bold text-sm text-gray-500 dark:text-gray-400 hover:text-red-500 dark:hover:text-red-400 transition tracking-wide" href="/hackershare.dev/sources"><svg class="feather mr-1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="margin-top: -2px;"><path d="M8 3H5a2 2 0 0 0-2 2v3m18 0V5a2 2 0 0 0-2-2h-3m0 18h3a2 2 0 0 0 2-2v-3M3 16v3a2 2 0 0 0 2 2h3"></path></svg>MORE
      </a>
    </div>
  </div>
</div>

app/views/shared/sources/_utm_medium.html.erb
<div class="stats-item relative bg-white dark:bg-gray-825 shadow-xl rounded p-4" style="height: 436px;">
  <div class="fade-enter-active">
    <%= render partial: 'shared/sources/nav' %>
    <div class="flex items-center mt-3 mb-2 justify-between text-gray-500 text-xs font-bold tracking-wide"><span>UTM Medium</span><span>Visitors</span>
    </div>
    <div style="position: relative;">
      <% @top_utm_mediums.each do |source| %>
        <% @max_medium ||= source.count %>
        <div class="flex items-center justify-between my-1 text-sm">
          <div class="w-full h-8" style="max-width: calc(100% - 4rem);">
            <div class="bg-blue-50 dark:bg-gray-500 dark:bg-opacity-15" style="width:  <%= number_to_percentage(100 * source.count / @max_medium.to_f, precision: 2) %>; height: 30px;">

            </div>
            <span class="flex px-2 dark:text-gray-300" style="margin-top: -26px;">
              <%= link_to site_path(@site, request.query_parameters.merge(utm_medium: source.utm_medium)), class: 'block truncate hover:underline' do %>
               <%= source.utm_medium %>
              <% end%>
            </span>
          </div><span class="font-medium dark:text-gray-200"><%= pretty_num(source.count) %></span>
        </div>
      <% end %>

    </div>

    <div class="text-center w-full absolute bottom-0 left-0 pb-3">
      <a class="leading-snug font-bold text-sm text-gray-500 dark:text-gray-400 hover:text-red-500 dark:hover:text-red-400 transition tracking-wide" href="/hackershare.dev/sources"><svg class="feather mr-1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="margin-top: -2px;"><path d="M8 3H5a2 2 0 0 0-2 2v3m18 0V5a2 2 0 0 0-2-2h-3m0 18h3a2 2 0 0 0 2-2v-3M3 16v3a2 2 0 0 0 2 2h3"></path></svg>MORE
      </a>
    </div>
  </div>
</div>

app/views/shared/sources/_utm_source.html.erb
<div class="stats-item relative bg-white dark:bg-gray-825 shadow-xl rounded p-4" style="height: 436px;">
  <div class="fade-enter-active">
    <%= render partial: 'shared/sources/nav' %>
    <div class="flex items-center mt-3 mb-2 justify-between text-gray-500 text-xs font-bold tracking-wide"><span>UTM Source</span><span>Visitors</span>
    </div>
    <div style="position: relative;">
      <% @top_utm_sources.each do |source| %>
        <% @max_source ||= source.count %>
        <div class="flex items-center justify-between my-1 text-sm">
          <div class="w-full h-8" style="max-width: calc(100% - 4rem);">
            <div class="bg-blue-50 dark:bg-gray-500 dark:bg-opacity-15" style="width:  <%= number_to_percentage(100 * source.count / @max_source.to_f, precision: 2) %>; height: 30px;">

            </div>
            <span class="flex px-2 dark:text-gray-300" style="margin-top: -26px;">
              <%= link_to site_path(@site, request.query_parameters.merge(utm_source: source.utm_source)), class: 'block truncate hover:underline' do %>
               <%= source.utm_source %>
              <% end%>
            </span>
          </div><span class="font-medium dark:text-gray-200"><%= pretty_num(source.count) %></span>
        </div>
      <% end %>

    </div>

    <div class="text-center w-full absolute bottom-0 left-0 pb-3">
      <a class="leading-snug font-bold text-sm text-gray-500 dark:text-gray-400 hover:text-red-500 dark:hover:text-red-400 transition tracking-wide" href=""><svg class="feather mr-1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="margin-top: -2px;"><path d="M8 3H5a2 2 0 0 0-2 2v3m18 0V5a2 2 0 0 0-2-2h-3m0 18h3a2 2 0 0 0 2-2v-3M3 16v3a2 2 0 0 0 2 2h3"></path></svg>MORE
      </a>
    </div>
  </div>
</div>