config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :sessions, only: [:create, :new]
  delete "sign_out", to: "sessions#destroy", as: :destroy_session
  resources :registrations, only: [:create, :new] do
    collection do
      get "verification"
      get "verify"
    end
  end
  resources :landing, only: [:index]
  root "landing#index"
  resources :sites do
    resources :location_urls, only: [:index]
    resources :countries, only: [:index]
    resources :referrer_sources, only: [:index]
    resources :traffic_mediums, only: [:index]
    resources :traffic_sources, only: [:index]
    resources :traffic_campaigns, only: [:index]
    resources :browsers, only: [:index]
    resources :device_types, only: [:index]
    resources :oses, only: [:index]

    resources :site_connections, only: [:index, :new, :show, :destroy, :create]
    resources :measurement_protocols, only: [:index, :new, :show, :destroy, :create]
    member do
      get "snippet"
      get "debug"
    end
    resources :settings, only: %i[index] do
      collection do
        get "general"
        patch "update_general"
      end

      collection do
        get "visibility"
        patch "update_visibility"
      end
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/devices/_browser.html.erb
<div class="stats-item">
  <div class="bg-white dark:bg-gray-825 shadow-xl rounded p-4 relative" style="height: 436px;">
    <%= render partial: 'shared/devices/nav' %>
    <div class="fade-enter-active">
      <div class="flex items-center mt-3 mb-2 justify-between text-gray-500 dark:text-gray-400 text-xs font-bold tracking-wide"><span>Browser</span><span>Visitors</span>
      </div>
      <% @top_browsers.each do |type| %>
        <% @max_browser ||= type.count %>
        <div class="flex items-center justify-between my-1 text-sm">
          <div class="w-full h-8" style="max-width: calc(100% - 6rem);">
            <div class="bg-green-50 dark:gray-500 dark:bg-opacity-15" style="width: <%= number_to_percentage(100 * type.count / @max_browser.to_f, precision: 2) %>; height: 30px;">

            </div>
            <span class="flex px-2 dark:text-gray-300" style="margin-top: -26px;">
              <%= link_to type.browser, site_path(@site, request.query_parameters.merge(browser: type.browser)), class: 'block hover:underline', title: type.browser %>
            </span>
          </div><span class="font-medium dark:text-gray-200"><%= pretty_num type.count %> <span class="inline-block text-xs w-8 text-right">(<%= number_to_percentage(100 * type.count / @unique_visitors_summary.to_f, precision: 1) %>)</span></span>
        </div>
      <% end %>
    </div>

    <div class="text-center w-full absolute bottom-0 left-0 pb-3">
      <a class="leading-snug font-bold text-sm text-gray-500 dark:text-gray-400 hover:text-red-500 dark:hover:text-red-400 transition tracking-wide" href="<%= site_browsers_path(@site, request.query_parameters) %>"><svg class="feather mr-1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="margin-top: -2px;"><path d="M8 3H5a2 2 0 0 0-2 2v3m18 0V5a2 2 0 0 0-2-2h-3m0 18h3a2 2 0 0 0 2-2v-3M3 16v3a2 2 0 0 0 2 2h3"></path></svg>MORE
      </a>
    </div>
  </div>
</div>

app/views/shared/devices/_device_type.html.erb
<div class="stats-item">
  <div class="bg-white dark:bg-gray-825 shadow-xl rounded p-4 relative" style="height: 436px;">
    <%= render partial: 'shared/devices/nav' %>
    <div class="fade-enter-active">
      <div class="flex items-center mt-3 mb-2 justify-between text-gray-500 dark:text-gray-400 text-xs font-bold tracking-wide"><span>Device Type</span><span>Visitors</span>
      </div>
      <% @top_device_types.each do |type| %>
        <% @max_device ||= type.count %>
        <div class="flex items-center justify-between my-1 text-sm">
          <div class="w-full h-8" style="max-width: calc(100% - 6rem);">
            <div class="bg-green-50 dark:gray-500 dark:bg-opacity-15" style="width: <%= number_to_percentage(100 * type.count / @max_device.to_f, precision: 2) %>; height: 30px;">

            </div>
            <span class="flex px-2 dark:text-gray-300" style="margin-top: -26px;">
               <%= link_to type.device_type, site_path(@site, request.query_parameters.merge(device_type: type.device_type)), class: 'block hover:underline', title: type.device_type %>
            </span>
          </div><span class="font-medium dark:text-gray-200"><%= pretty_num type.count %> <span class="inline-block text-xs w-8 text-right">(<%= number_to_percentage(100 * type.count / @unique_visitors_summary.to_f, precision: 1) %>)</span></span>
        </div>
      <% end %>
    </div>

    <div class="text-center w-full absolute bottom-0 left-0 pb-3">
      <a class="leading-snug font-bold text-sm text-gray-500 dark:text-gray-400 hover:text-red-500 dark:hover:text-red-400 transition tracking-wide" href="<%= site_device_types_path(@site, request.query_parameters) %>"><svg class="feather mr-1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="margin-top: -2px;"><path d="M8 3H5a2 2 0 0 0-2 2v3m18 0V5a2 2 0 0 0-2-2h-3m0 18h3a2 2 0 0 0 2-2v-3M3 16v3a2 2 0 0 0 2 2h3"></path></svg>MORE
      </a>
    </div>
  </div>
</div>

app/views/shared/devices/_nav.html.erb
<div class="w-full flex justify-between">
  <h3 class="font-bold dark:text-gray-100">Top Devices</h3>
  <ul class="flex font-medium text-xs text-gray-500 dark:text-gray-400 space-x-2">
    <li class="<%= device_tab_class(:device_type) %>"><%= link_to "Device Type", site_path(@site, **params.permit.merge(device_meniu: :device_type), anchor: 'top_devices') %></li>
    <li class="<%= device_tab_class(:browser) %>"><%= link_to "Browser", site_path(@site, **params.permit.merge(device_meniu: :browser), anchor: 'top_devices') %></li>
    <li class="<%= device_tab_class(:os) %>"><%= link_to "OS", site_path(@site, **params.permit.merge(device_meniu: :os), anchor: 'top_devices') %></li>
  </ul>
</div>

app/views/shared/devices/_os.html.erb
<div class="stats-item">
  <div class="bg-white dark:bg-gray-825 shadow-xl rounded p-4 relative" style="height: 436px;">
    <%= render partial: 'shared/devices/nav' %>
    <div class="fade-enter-active">
      <div class="flex items-center mt-3 mb-2 justify-between text-gray-500 dark:text-gray-400 text-xs font-bold tracking-wide"><span>OS</span><span>Visitors</span>
      </div>
      <% @top_oses.each do |type| %>
        <% @max_os ||= type.count %>
        <div class="flex items-center justify-between my-1 text-sm">
          <div class="w-full h-8" style="max-width: calc(100% - 6rem);">
            <div class="bg-green-50 dark:gray-500 dark:bg-opacity-15" style="width: <%= number_to_percentage(100 * type.count / @max_os.to_f, precision: 2) %>; height: 30px;">

            </div>
            <span class="flex px-2 dark:text-gray-300" style="margin-top: -26px;">
              <%= link_to type.os, site_path(@site, request.query_parameters.merge(device_type: type.os)), class: 'block hover:underline', title: type.os %>
            </span>
          </div><span class="font-medium dark:text-gray-200"><%= pretty_num type.count %> <span class="inline-block text-xs w-8 text-right">(<%= number_to_percentage(100 * type.count / @unique_visitors_summary.to_f, precision: 1) %>)</span></span>
        </div>
      <% end %>
    </div>

    <div class="text-center w-full absolute bottom-0 left-0 pb-3">
      <a class="leading-snug font-bold text-sm text-gray-500 dark:text-gray-400 hover:text-red-500 dark:hover:text-red-400 transition tracking-wide" href="<%= site_oses_path(@site, request.query_parameters) %>"><svg class="feather mr-1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="margin-top: -2px;"><path d="M8 3H5a2 2 0 0 0-2 2v3m18 0V5a2 2 0 0 0-2-2h-3m0 18h3a2 2 0 0 0 2-2v-3M3 16v3a2 2 0 0 0 2 2h3"></path></svg>MORE
      </a>
    </div>
  </div>
</div>