config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :sessions, only: [:create, :new]
  delete "sign_out", to: "sessions#destroy", as: :destroy_session
  resources :registrations, only: [:create, :new] do
    collection do
      get "verification"
      get "verify"
    end
  end
  resources :landing, only: [:index]
  root "landing#index"
  resources :sites do
    resources :location_urls, only: [:index]
    resources :countries, only: [:index]
    resources :referrer_sources, only: [:index]
    resources :traffic_mediums, only: [:index]
    resources :traffic_sources, only: [:index]
    resources :traffic_campaigns, only: [:index]
    resources :browsers, only: [:index]
    resources :device_types, only: [:index]
    resources :oses, only: [:index]

    resources :site_connections, only: [:index, :new, :show, :destroy, :create]
    resources :measurement_protocols, only: [:index, :new, :show, :destroy, :create]
    member do
      get "snippet"
      get "debug"
    end
    resources :settings, only: %i[index] do
      collection do
        get "general"
        patch "update_general"
      end

      collection do
        get "visibility"
        patch "update_visibility"
      end
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_date_filter.html.erb
<div class="flex justify-end ml-auto pl-2">
  <div x-data="{ open: false }" @click.away="open = false" class="relative" style="height: 35.5px; width: 190px;">
    <div @click="open = !open" class="flex items-center justify-between rounded bg-white dark:bg-gray-800 shadow px-4 pr-3 py-2 leading-tight cursor-pointer text-sm font-medium text-gray-800 dark:text-gray-200 h-full" id="options-menu" aria-haspopup="true" aria-expanded="true" tabindex="0"><span class="mr-2"><%= time_range_names[params[:period]] %></span>
      <svg class="text-indigo-500 h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="6 9 12 15 18 9"></polyline>
      </svg>
    </div>
    <div x-show="open" x-description="Profile dropdown panel, show/hide based on dropdown state." x-transition:enter="transition ease-out duration-100" x-transition:enter-start="transform opacity-0 scale-95" x-transition:enter-end="transform opacity-100 scale-100" x-transition:leave="transition ease-in duration-75" x-transition:leave-start="transform opacity-100 scale-100" x-transition:leave-end="transform opacity-0 scale-95" class="origin-top-left absolute left-0 mt-2 w-48 rounded-md shadow-lg z-10" style="display: none;">
      <div class="py-1 rounded-md bg-white shadow-xs" role="menu" aria-orientation="vertical" aria-labelledby="user-menu">
        <% %w[realtime 7d 30d 6m 12m today week month].each do |filter| %>
          <%= link_to time_range_names[filter], request.params.merge(period: filter), class: 'bg-gray-100 block px-2 py-1 lg:px-4 lg:py-2 text-sm leading-5 text-gray-700 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 transition duration-150 ease-in-out', role: 'menuitem' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_growth_rate.html.erb
<% if growth.na? %>
  <span class="text-xs text-gray-700 dark:text-gray-300">〰 N/A</span>
<% elsif growth.positive?%>
  <span class="text-xs text-green-500 font-bold">↑</span> <%= number_to_percentage growth.growth_rate, precision: 0 %></span>
<% else %>
  <span class="text-xs text-red-400 font-bold">↓</span> <%= number_to_percentage growth.growth_rate,  precision: 0 %>
<% end %>

app/views/shared/_sql.html.erb
<div class="border-b border-gray-300">
  <pre class="text-sm text-gray-800">
    <%= simple_format @sql %>
  </pre>
</div>

app/views/shared/_steps.html.erb
<div class="pt-12 pl-8 hidden md:block">
  <div class="pt-6 px-4 sm:px-6 lg:px-8">
    <nav class="flex justify-center">
      <ol class="space-y-6">



            <!-- Current Step -->
            <li class="flex items-start">
              <span class="flex-shrink-0 h-5 w-5 relative flex items-center justify-center">
                <span class="absolute h-4 w-4 rounded-full bg-indigo-200 dark:bg-indigo-100"></span>
                <span class="relative block w-2 h-2 bg-indigo-600 dark:bg-indigo-500 rounded-full"></span>
              </span>
              <span class="ml-3 text-sm font-medium text-indigo-600 dark:text-indigo-500">Register</span>
            </li>






            <!-- Upcoming Step -->
            <li class="flex items-start">
              <div class="flex-shrink-0 h-5 w-5 relative flex items-center justify-center">
                <div class="h-2 w-2 bg-gray-300 dark:bg-gray-700 rounded-full"></div>
              </div>
              <p class="ml-3 text-sm font-medium text-gray-500 dark:text-gray-300">Activate account</p>
            </li>





            <!-- Upcoming Step -->
            <li class="flex items-start">
              <div class="flex-shrink-0 h-5 w-5 relative flex items-center justify-center">
                <div class="h-2 w-2 bg-gray-300 dark:bg-gray-700 rounded-full"></div>
              </div>
              <p class="ml-3 text-sm font-medium text-gray-500 dark:text-gray-300">Add site info</p>
            </li>





            <!-- Upcoming Step -->
            <li class="flex items-start">
              <div class="flex-shrink-0 h-5 w-5 relative flex items-center justify-center">
                <div class="h-2 w-2 bg-gray-300 dark:bg-gray-700 rounded-full"></div>
              </div>
              <p class="ml-3 text-sm font-medium text-gray-500 dark:text-gray-300">Install snippet</p>
            </li>


      </ol>
    </nav>
  </div>

</div>

app/views/shared/_summary.html.erb
<div class="flex flex-wrap">
  <div class="px-8 w-1/2 my-4 lg:w-auto  border-r lg:border-r-0">
    <div class="text-gray-500 dark:text-gray-400 text-xs font-bold tracking-wide uppercase">Unique visitors
    </div>
    <div class="my-1 flex justify-between items-center">
      <b class="text-2xl mr-4 dark:text-gray-100"><%= pretty_num @unique_visitors_summary %></b>
      <span class="text-xs dark:text-gray-100">
        <%= render partial: 'shared/growth_rate', locals: {growth: GrowthRate.new(@unique_visitors_summary_p, @unique_visitors_summary)} %>
      </span>
    </div>
  </div>

  <div class="px-8 w-1/2 my-4 lg:w-auto lg:border-l border-gray-300">
    <div class="text-gray-500 dark:text-gray-400 text-xs font-bold tracking-wide uppercase">Total pageviews
    </div>

    <div class="my-1 flex justify-between items-center"><b class="text-2xl mr-4 dark:text-gray-100"><%= pretty_num @total_pageviews_summary %></b>
      <span class="text-xs dark:text-gray-100">
        <%= render partial: 'shared/growth_rate', locals: {growth: GrowthRate.new(@total_pageviews_summary_p, @total_pageviews_summary)} %>
      </span>
    </div>
  </div>
  <div class="px-8 w-1/2 my-4 lg:w-auto lg:border-l border-gray-300 border-r lg:border-r-0">  <div class="text-gray-500 dark:text-gray-400 text-xs font-bold tracking-wide uppercase">New visitors
  </div>
  <div class="my-1 flex justify-between items-center">
    <b class="text-2xl mr-4 dark:text-gray-100">
      <%= pretty_num(@new_visitors_count) %></b>
      <span class="text-xs dark:text-gray-100">
        <%= render partial: 'shared/growth_rate', locals: {growth: GrowthRate.new(@new_visitors_count_p, @new_visitors_count)} %>
      </span>
  </div>
</div>
<div class="px-8 w-1/2 my-4 lg:w-auto lg:border-l border-gray-300">
  <div class="text-gray-500 dark:text-gray-400 text-xs font-bold tracking-wide uppercase">Avg Engagement Time
  </div>
  <div class="my-1 flex justify-between items-center">
    <b class="text-2xl mr-4 dark:text-gray-100"><%= pretty_time(@avg_engagement_time.to_i / 1000) %></b>
    <span class="text-xs dark:text-gray-100">
      <%= render partial: 'shared/growth_rate', locals: {growth: GrowthRate.new(@avg_engagement_time_p, @avg_engagement_time)} %>
    </div>
  </div>
</div>

app/views/shared/_top_country.html.erb
<script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.3/d3.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/topojson/3.0.2/topojson.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/datamaps/0.5.9/datamaps.world.min.js"></script>
<div class="stats-item relative bg-white dark:bg-gray-825 shadow-xl rounded p-4" style="height: 436px;">
  <div class="fade-enter-active"><h3 class="font-bold dark:text-gray-100">Countries or regions</h3>
    <div class="mt-6 mx-auto" id="map-container" style="width: 100%; max-width: 475px; height: 320px; position: relative; padding-bottom: 56.25%;">
      
    </div>
  </div>
  <div class="text-center w-full absolute bottom-0 left-0 pb-3">
      <a class="leading-snug font-bold text-sm text-gray-500 dark:text-gray-400 hover:text-red-500 dark:hover:text-red-400 transition tracking-wide" href="<%= site_countries_path(@site, request.query_parameters) %>"><svg class="feather mr-1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="margin-top: -2px;"><path d="M8 3H5a2 2 0 0 0-2 2v3m18 0V5a2 2 0 0 0-2-2h-3m0 18h3a2 2 0 0 0 2-2v-3M3 16v3a2 2 0 0 0 2 2h3"></path></svg>MORE
      </a>
    </div>
</div>

<script>
  var label =  'Visitors'
  var defaultFill =  '#f8fafc'
  var highlightFill =  '#F5F5F5'
  var borderColor =  '#dae1e7'
  var highlightBorderColor = '#a779e9'

  var series = <%= @top_countries.html_safe %>;


    // Datamaps expect data in format:
    // { "USA": { "fillColor": "#42a844", numberOfWhatever: 75},
    //   "FRA": { "fillColor": "#8dc386", numberOfWhatever: 43 } }
    var dataset = {};

    // We need to colorize every country based on "numberOfWhatever"
    // colors should be uniq for every value.
    // For this purpose we create palette(using min/max series-value)
    var onlyValues = series.map(function(obj){ return obj[1]; });
    var minValue = Math.min.apply(null, onlyValues),
    maxValue = Math.max.apply(null, onlyValues);

    // create color palette function
    // color can be whatever you wish
    var paletteScale = d3.scale.linear()
    .domain([minValue,maxValue])
            .range(["#EFEFFF","#02386F"]); // blue color

    // fill dataset in appropriate format
    series.forEach(function(item){ //
        // item example value ["USA", 70]
        var iso = item[0],
        value = item[1];
        dataset[iso] = { numberOfThings: value, fillColor: paletteScale(value) };
      });
    var map = new Datamap(
    {
      element: document.getElementById('map-container'),
      done: function(datamap) {
        datamap.svg.selectAll('.datamaps-subunit').on('click', function(geography) {
            //alert(geography.properties.name);
            var url = new URL(window.location);
            url.searchParams.set('country', geography.properties.name);
            window.location = url.toString();
        });
      },

      responsive: true,
      projection: 'mercator',
      fills: { defaultFill },
      data: dataset,
      geographyConfig: {
        borderColor,
        highlightBorderWidth: 2,
        highlightFillColor: function(geo) {
          return geo['fillColor'] || highlightFill;
        },
        highlightBorderColor,
        popupTemplate: function(geo, data) {
          console.log(geo)
          console.log(data)
          if (!data) { return ; }
          const pluralizedLabel = data.numberOfThings === 1 ? label.slice(0, -1) : label
          return ['<div class="hoverinfo dark:bg-gray-800 dark:shadow-gray-850 dark:border-gray-850 dark:text-gray-200">',
          '<strong>', geo.properties.name, '</strong>',
          '<br><strong class="dark:text-indigo-400">', data.numberOfThings, '</strong> ' + pluralizedLabel,
          '</div>'].join('');
        }
      }
    }
    );
 </script>

app/views/shared/_top_device.html.erb
<div class="stats-item">
  <div class="bg-white dark:bg-gray-825 shadow-xl rounded p-4 relative" style="height: 436px;">
    <div class="w-full flex justify-between">
      <h3 class="font-bold dark:text-gray-100">Devices</h3>
      <ul class="flex font-medium text-xs text-gray-500 dark:text-gray-400 space-x-2">
        <li class="inline-block h-5 text-indigo-700 dark:text-indigo-500 font-bold border-b-2 border-indigo-700 dark:border-indigo-500">Device</li>
        <li class="hover:text-indigo-600 cursor-pointer">Browser</li>
        <li class="hover:text-indigo-600 cursor-pointer">OS</li>
      </ul>
    </div>
    <div class="fade-enter-active">
      <div class="flex items-center mt-3 mb-2 justify-between text-gray-500 dark:text-gray-400 text-xs font-bold tracking-wide"><span>Device Type</span><span>Visitors</span>
      </div>
      <% @top_device_types.each do |type| %>
        <% @max_device ||= type.count %>
        <div class="flex items-center justify-between my-1 text-sm">
          <div class="w-full h-8" style="max-width: calc(100% - 6rem);">
            <div class="bg-green-50 dark:gray-500 dark:bg-opacity-15" style="width: <%= number_to_percentage(100 * type.count / @max_device.to_f, precision: 2) %>; height: 30px;">

            </div><span class="flex px-2 dark:text-gray-300" style="margin-top: -26px;"><a class="block truncate hover:underline" href="/?os=Windows"><%= type.device_type %></a></span>
          </div><span class="font-medium dark:text-gray-200"><%= pretty_num type.count %> <span class="inline-block text-xs w-8 text-right">(<%= number_to_percentage(100 * type.count / @max_device.to_f, precision: 0) %>)</span></span>
        </div>
      <% end %>
    </div>

    <div class="text-center w-full absolute bottom-0 left-0 pb-3">
      <a class="leading-snug font-bold text-sm text-gray-500 dark:text-gray-400 hover:text-red-500 dark:hover:text-red-400 transition tracking-wide" href="/hackershare.dev/pages"><svg class="feather mr-1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="margin-top: -2px;"><path d="M8 3H5a2 2 0 0 0-2 2v3m18 0V5a2 2 0 0 0-2-2h-3m0 18h3a2 2 0 0 0 2-2v-3M3 16v3a2 2 0 0 0 2 2h3"></path></svg>MORE
      </a>
    </div>
  </div>
</div>

app/views/shared/_top_page.html.erb
<div class="stats-item relative bg-white dark:bg-gray-825 shadow-xl rounded p-4" style="height: 436px;">
  <div class="fade-enter-active">
    <h3 class="font-bold dark:text-gray-100">Top Pages</h3>
    <div class="flex items-center mt-3 mb-2 justify-between text-gray-500 dark:text-gray-400 text-xs font-bold tracking-wide"><span>Page url</span><span>Visitors</span>
    </div>
    <div style="position: relative;">
      <% @top_pages.each do |page| %>
      <% @max_page ||= page.count %>
        <div class="flex items-center justify-between my-1 text-sm">
          <div class="w-full h-8 truncate" style="max-width: calc(100% - 4rem);">
            <div class="bg-orange-50 dark:bg-gray-500 dark:bg-opacity-15" style="width: <%= (page.count / @max_page.to_f) * 100 %>%; height: 30px;">

            </div>
            <span class="flex px-2 group dark:text-gray-300" style="margin-top: -26px;">
              <%= link_to url_to_path(page.location_url), site_path(@site, request.query_parameters.merge(location_url: page.location_url)), class: 'block hover:underline', title: page.location_url %>
              <a target="_blank" href="<%= page.location_url %>" class="hidden group-hover:block"><svg class="inline h-4 w-4 ml-1 -mt-1 text-gray-600 dark:text-gray-400" fill="currentColor" viewBox="0 0 20 20"><path d="M11 3a1 1 0 100 2h2.586l-6.293 6.293a1 1 0 101.414 1.414L15 6.414V9a1 1 0 102 0V4a1 1 0 00-1-1h-5z"></path><path d="M5 5a2 2 0 00-2 2v8a2 2 0 002 2h8a2 2 0 002-2v-3a1 1 0 10-2 0v3H5V7h3a1 1 0 000-2H5z"></path></svg></a>
            </span>
          </div><span class="font-medium dark:text-gray-200"><%= pretty_num page.count %></span>
        </div>
      <% end %>
    </div>

    <div class="text-center w-full absolute bottom-0 left-0 pb-3">
      <a class="leading-snug font-bold text-sm text-gray-500 dark:text-gray-400 hover:text-red-500 dark:hover:text-red-400 transition tracking-wide" href="<%= site_location_urls_path(@site, request.query_parameters) %>"><svg class="feather mr-1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="margin-top: -2px;"><path d="M8 3H5a2 2 0 0 0-2 2v3m18 0V5a2 2 0 0 0-2-2h-3m0 18h3a2 2 0 0 0 2-2v-3M3 16v3a2 2 0 0 0 2 2h3"></path></svg>MORE
      </a>
    </div>
  </div>
</div>