config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :sessions, only: [:create, :new]
  delete "sign_out", to: "sessions#destroy", as: :destroy_session
  resources :registrations, only: [:create, :new] do
    collection do
      get "verification"
      get "verify"
    end
  end
  resources :landing, only: [:index]
  root "landing#index"
  resources :sites do
    resources :location_urls, only: [:index]
    resources :countries, only: [:index]
    resources :referrer_sources, only: [:index]
    resources :traffic_mediums, only: [:index]
    resources :traffic_sources, only: [:index]
    resources :traffic_campaigns, only: [:index]
    resources :browsers, only: [:index]
    resources :device_types, only: [:index]
    resources :oses, only: [:index]

    resources :site_connections, only: [:index, :new, :show, :destroy, :create]
    resources :measurement_protocols, only: [:index, :new, :show, :destroy, :create]
    member do
      get "snippet"
      get "debug"
    end
    resources :settings, only: %i[index] do
      collection do
        get "general"
        patch "update_general"
      end

      collection do
        get "visibility"
        patch "update_visibility"
      end
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/settings_controller.rb
# frozen_string_literal: true

class SettingsController < ApplicationController
  before_action :get_site

  def general
  end

  def update_general
    @site.update(params.require(:site).permit(:timezone, :domain, :tracking_id))
    if @site.valid?
      flash[:success] = "Site update successfully."
      redirect_back fallback_location: general_site_settings_path(@site)
    else
      flash[:error] = "Site update failed"
      render "general"
    end
  end

  def visibility
  end

  def update_visibility
  end

  def get_site
    @site = current_user.sites.find_by!(uuid: params[:site_id])
  end
end

app/views/settings/_nav.html.erb
<div class="py-4 g:py-0 lg:col-span-3">
  <form action="" class="lg:hidden" method="post">
    <select class="dark:bg-gray-800 mt-1 block w-full pl-3 pr-10 py-2 text-base border-gray-300 dark:border-gray-500 outline-none focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm rounded-md dark:text-gray-100" id="tab" name="tab" onchange="location.href = event.target.value">
      <option value="<%= general_site_settings_path(@site)  %>" selected="">General</option>
      <option value="<%= site_site_connections_path(@site) %>">Site Connection</option>
      <option value="<%= site_measurement_protocols_path(@site) %>">Measurement Protocol</option>
    </select>
  </form>
  <div class="hidden lg:block">

    <a href="<%= general_site_settings_path(@site) %>" class="flex items-center px-3 py-2 text-sm leading-5 font-medium  transition ease-in-out duration-150  <%= render_setting_nav_css(:general) %>">General</a>



    <a href="<%= site_site_connections_path(@site) %>" class="flex items-center px-3 py-2 text-sm leading-5 font-medium  transition ease-in-out duration-150  <%= render_setting_nav_css(:site_connection) %> mt-1">Connection</a>

    <a href="<%= site_measurement_protocols_path(@site) %>" class="flex items-center px-3 py-2 text-sm leading-5 font-medium  transition ease-in-out duration-150  <%= render_setting_nav_css(:measurement_protocol) %> mt-1">Measurement Protocol</a>



  </div>
</div>

app/views/settings/general.html.erb
<div class="container pt-6">
  <a class="text-sm text-indigo-600 font-bold" href="<%= site_path(@site) %>">← Back to stats</a>
  <div class="pb-5 border-b border-gray-200 dark:border-gray-500">
    <h2 class="text-2xl font-bold leading-7 text-gray-900 dark:text-gray-100 sm:text-3xl sm:leading-9 sm:truncate">
      Settings for <%= @site.domain %>
    </h2>
  </div>
  <div class="lg:grid lg:grid-cols-12 lg:gap-x-5 lg:mt-4">
    <%= render partial: 'nav' %>

    <div class="space-y-6 lg:col-span-9 lg:mt-4">
      <%= form_with model: @site, local: true, url: update_general_site_settings_path(@site) do |f| %>
      <div class="shadow sm:rounded-md sm:overflow-hidden">
        <div class="bg-white dark:bg-gray-800 py-6 px-4 space-y-6 sm:p-6">
          <header class="relative">
            <h2 class="text-lg leading-6 font-medium text-gray-900 dark:text-gray-100">General information</h2>
            <p class="mt-1 text-sm leading-5 text-gray-500 dark:text-gray-200">Update your reporting timezone.</p>
            <a href="" target="_blank">
              <svg class="w-6 h-6 absolute top-0 right-0 text-gray-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd"></path></svg>
            </a>
          </header>

          <div class="grid grid-cols-4 gap-6">
            <div class="col-span-4 sm:col-span-2"> 
              <%= f.label 'Domain', class: 'block text-sm font-medium leading-5 text-gray-700 dark:text-gray-300' %>
              <%= f.text_field :domain, class: 'dark:bg-gray-900 mt-1 block w-full shadow-sm focus:ring-indigo-500 focus:border-indigo-500 sm:max-w-xs sm:text-sm border-gray-300 dark:border-gray-500 rounded-md dark:text-gray-100' %>
            </div>

            <div class="col-span-4 sm:col-span-2">
              <%= f.label 'Timezone', class: 'block text-sm font-medium leading-5 text-gray-700 dark:text-gray-300' %>
              <%= f.time_zone_select(:timezone, ActiveSupport::TimeZone.all, {default: "UTC"}, class: "dark:bg-gray-900  mt-1 block w-full pl-3 pr-10 py-2 text-base border-gray-300 dark:border-gray-500 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm rounded-md dark:text-gray-100 cursor-pointer") %>
            </div>
          </div>

          <div class="grid grid-cols-4 gap-6">
            <div class="col-span-4 sm:col-span-2"> 
              <%= f.label 'tracking_id', class: 'block text-sm font-medium leading-5 text-gray-700 dark:text-gray-300' %>
              <%= f.text_field :tracking_id, class: 'dark:bg-gray-900 mt-1 block w-full shadow-sm focus:ring-indigo-500 focus:border-indigo-500 sm:max-w-xs sm:text-sm border-gray-300 dark:border-gray-500 rounded-md dark:text-gray-100' %>
            </div>
          </div>

        </div>
        <div class="px-4 py-3 bg-gray-50 dark:bg-gray-850 text-right sm:px-6">
          <span class="inline-flex rounded-md shadow-sm">
            <%= f.button 'Save', class: 'button', type: :submit, data: {disable_with: disable_with_spinner('Save')} %>
          </span>
        </div>
      </div>
      <% end %>

      <form action="/" class="shadow bg-white dark:bg-gray-800 sm:rounded-md sm:overflow-hidden py-6 px-4 sm:p-6" method="post">
        <header class="relative">
          <h2 class="text-lg leading-6 font-medium text-gray-900 dark:text-gray-100">Javascript snippet</h2>
          <p class="mt-1 text-sm leading-5 text-gray-500 dark:text-gray-200">Include this snippet in the <code>&lt;head&gt;</code> of your website.</p>
          <a href="" target="_blank">
            <svg class="w-6 h-6 absolute top-0 right-0 text-gray-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd"></path></svg>
          </a>
        </header>

        <div class="my-4">
          <div class="relative">
            <textarea class="transition overflow-hidden bg-gray-100 dark:bg-gray-900 outline-none appearance-none border border-transparent rounded w-full p-2 pr-6 text-gray-700 dark:text-gray-300 leading-normal focus:outline-none focus:bg-white focus:border-gray-300 dark:focus:border-gray-500 text-xs mt-2 resize-none" id="snippet_code" name="domain" rows="10">
              <!-- Global site tag (gtag.js) - Google Analytics -->
              <script async src="https://www.googletagmanager.com/gtag/js?id=<%= @site.tracking_id %>"></script>
              <script>
                window.dataLayer = window.dataLayer || [];
                function gtag(){dataLayer.push(arguments);}
                gtag('js', new Date());

                gtag('config', '<%= @site.tracking_id %>', {transport_url: '<%= collector_server_url(@site) %>'});
                // replay payload to google analytics
                gtag('config', '<%= @site.tracking_id %>');
              </script>

            </textarea>
            <a onclick="var textarea = document.getElementById('snippet_code'); textarea.focus(); textarea.select(); document.execCommand('copy');" href="javascript:void(0)" class="no-underline text-indigo-500 text-sm hover:underline">
              <svg class="absolute text-indigo-500" style="top: 24px; right: 12px;" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg>
            </a>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>

app/views/settings/visibility.html.erb
<div class="container pt-6">
  <a class="text-sm text-indigo-600 font-bold" href="<%= site_path(@site) %>">← Back to stats</a>
  <div class="pb-5 border-b border-gray-200 dark:border-gray-500">
    <h2 class="text-2xl font-bold leading-7 text-gray-900 dark:text-gray-100 sm:text-3xl sm:leading-9 sm:truncate">
      Settings for <%= @site.domain %>
    </h2>
  </div>
  <div class="lg:grid lg:grid-cols-12 lg:gap-x-5 lg:mt-4">
    <%= render partial: 'nav' %>

    <div class="space-y-6 lg:col-span-9 lg:mt-4">
      <%= form_with model: @site, local: true, url: update_general_site_settings_path(@site) do |f| %>
      <div class="shadow sm:rounded-md sm:overflow-hidden">
        <div class="bg-white dark:bg-gray-800 py-6 px-4 space-y-6 sm:p-6">
          <header class="relative">
            <h2 class="text-lg leading-6 font-medium text-gray-900 dark:text-gray-100">General information</h2>
            <p class="mt-1 text-sm leading-5 text-gray-500 dark:text-gray-200">Update your reporting timezone.</p>
            <a href="" target="_blank">
              <svg class="w-6 h-6 absolute top-0 right-0 text-gray-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd"></path></svg>
            </a>
          </header>

          <div class="grid grid-cols-4 gap-6">
            <div class="col-span-4 sm:col-span-2"> 
              <%= f.label 'Domain', class: 'block text-sm font-medium leading-5 text-gray-700 dark:text-gray-300' %>
              <%= f.text_field :domain, class: 'dark:bg-gray-900 mt-1 block w-full shadow-sm focus:ring-indigo-500 focus:border-indigo-500 sm:max-w-xs sm:text-sm border-gray-300 dark:border-gray-500 rounded-md dark:text-gray-100' %>
            </div>

            <div class="col-span-4 sm:col-span-2">
              <%= f.label 'Timezone', class: 'block text-sm font-medium leading-5 text-gray-700 dark:text-gray-300' %>
              <%= f.time_zone_select(:timezone, ActiveSupport::TimeZone.all, {default: "UTC"}, class: "dark:bg-gray-900  mt-1 block w-full pl-3 pr-10 py-2 text-base border-gray-300 dark:border-gray-500 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm rounded-md dark:text-gray-100 cursor-pointer") %>
            </div>
          </div>
        </div>
        <div class="px-4 py-3 bg-gray-50 dark:bg-gray-850 text-right sm:px-6">
          <span class="inline-flex rounded-md shadow-sm">
            <%= f.button 'Save', class: 'button', type: :submit, data: {disable_with: disable_with_spinner('Save')} %>
          </span>
        </div>
      </div>
      <% end %>

    </div>
  </div>
</div>